### PR TITLE
ENH: Configure isolated builds and set up cibuildwheel

### PR DESCRIPTION
**Pull request by effigies**
Builds on #13 and #14.

Incremental diff: https://github.com/effigies/gradunwarp/compare/mnt/drop-fsl...enh/build

Closes #13.
Closes #14.

### CODE REVIEW

**Comment by effigies** [comment]
I believe the test failure was a one-off corrupt download from PyPI. Restarting the CI job should check that. This is ready for review.

**Comment by coalsont** [comment]
Looks reasonable as far as I can tell.  Seems to still install with the old instructions on ubuntu 20.04/python3.8 at least (if the system numpy isn't installed, but that was already an issue in our version).  Haven't tried anything more than the usage info.

**Comment by cyang31** [comment]
Looks good to me. The replacement of the command line with the nibabel module is really nice. I created a local env on macos, installed this module using this PR, run the test_gradient_unwarp.py and it works on my end.

**Comment by effigies** [comment]
I should note that I added some machinery for bumping the version across the three locations it's found in. It uses [bumpver](https://github.com/mbarkhau/bumpver), which can be installed with pip or run through something like [pipx](https://github.com/pypa/pipx/):

```console
❯ pipx run bumpver show         
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
Current Version: 1.2.2.dev
PEP440         : 1.2.2.dev0
```

To update from a dev version, you can run `bumpver update --tag final`. Here I bump the minor version from 1.2 to 1.3 (using `--dry` to avoid making a commit or tag):

```console
❯ pipx run bumpver update --minor --tag final --dry
INFO    - fetching tags from remote (to turn off use: -n / --no-fetch)
INFO    - Old Version: 1.2.2.dev
INFO    - New Version: 1.3.0
--- gradunwarp/core/globals.py
+++ gradunwarp/core/globals.py
@@ -6,7 +6,7 @@
 ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ### ##
 import logging
 
-VERSION = '1.2.2.dev'
+VERSION = '1.3.0'
 
 usage = '''
 gradient_unwarp infile outfile manufacturer -g <coefficient file> [optional arguments]
--- pyproject.toml
+++ pyproject.toml
@@ -13,7 +13,7 @@
 build-backend = "setuptools.build_meta"
 
 [tool.bumpver]
-current_version = "1.2.2.dev"
+current_version = "1.3.0"
 version_pattern = "MAJOR.MINOR.PATCH[.TAG]"
 commit_message = "bump version {old_version} -> {new_version}"
 tag_message = "{new_version}"
--- version.txt
+++ version.txt
@@ -1,2 +1,2 @@
-v1.2.2.dev
+v1.3.0
 
 ```

Dropping the `--minor` would update from `1.2.2.dev` to `1.2.2`.

Post-release, I would then do something like the following to update the dev version again:

```console
❯ pipx run bumpver update --patch --tag dev --no-tag-commit
```

**Comment by effigies** [comment]
Forgot that I planned to make sure `pip install .` works with and without pre-running `pip install -r requirements.txt`. Now included as a test and works across all listed versions.

**Comment by coalsont** [comment]
I'm basically just waiting for this to stabilize before merging.

**Comment by effigies** [comment]
Ah, I think this is good to go. If more things come up, more pull requests can be made.

**Pull request merged**
