### PR TITLE
Full Python 3 support

### PR DESCRIPTION
**Pull request by igor-raits**

### CODE REVIEW

**Comment by igor-raits** [comment]
pin @Washington-University

**Comment by glasserm** [comment]
I don't write python so I have requested Keith take a look.

**Comment by kjamison** [comment]
The changes look sane but I haven't vetted it in situ yet, which I'd like to do before signing off.

**Comment by crubb** [comment]
Hey, any progress on in-situ vetting it? ;)

**Comment by glasserm** [comment]
That would be @kjamison

**Comment by kjamison** [comment]
I had to make one additional modification to get it to run on python3 (and confirmed that it produces identical outputs). I'll make a new branch for the whole thing. 

However, converting a single T1 volume (320x320x256, 0.7mm iso) took 8 minutes in py3, compared to 45 seconds in python2.7! I'm not sure why that would happen, and don't really know where to start fixing it.

**Comment by crubb** [comment]
Dear @kjamison,

I suppose you needed to add something along the lines of

```
Additional small patch to establish Python3 compatibility. -- https://github.com/crubb (2020-01-11)

diff -ur gradunwarp-1.1.0/gradunwarp/core/gradient_unwarp.py gradunwarp-1.1.0-ArgumentParser/gradunwarp/core/gradient_unwarp.py
--- gradunwarp-1.1.0/gradunwarp/core/gradient_unwarp.py	2018-09-24 17:10:29.000000000 +0000
+++ gradunwarp-1.1.0-ArgumentParser/gradunwarp/core/gradient_unwarp.py	2020-01-11 14:06:35.327654857 +0000
@@ -18,7 +18,7 @@
     '''Arguments parser from the command line
     '''
     # initiate
-    p = arg.ArgumentParser(version=globals.VERSION, usage=globals.usage)
+    p = arg.ArgumentParser(usage=globals.usage)
 
     # required arguments
     p.add_argument('infile', action='store',
```

?

Please be advised, that, after we have applied the patch in this PR plus the patch above, and ran gradunwarp on a freshly acquired scan using the HCP Lifespan protocol, the `*_gdc.nii.gz` was actually flipped in the left-right direction on the axial axis. This did not happen with the unpatched gradunwarp release v1.1.0 with Python 2.7.15.

We used dcm2niix v1.0.20190902, FSL v6.0.2, Python 3.7.2, [SciPy-bundle 2019.03 from easybuild](https://github.com/easybuilders/easybuild-easyconfigs/blob/700d15d3eeb17e83dd5b15ab35aac4958e9f18d9/easybuild/easyconfigs/s/SciPy-bundle/SciPy-bundle-2019.03-foss-2019a.eb), and NiBabel v2.4.0.

**Comment by kjamison** [comment]
Yes it was basically that argparse change.

1. Did you see the same slowdown in Python 3 compared to 2.7?
2. I don't get any axis flipping in my outputs. Do you know if you ran fslreorient2std on the inputs before running gradient_unwarp.py?

I was running this on raw HCP 3T scans. I'm not sure which specific version of dcm2nii was used (though I think it preceded the existence of dcm2niix?)

**Comment by kjamison** [comment]
OK so the slowdown was simply because the py3 branch (2015) was before I moved the subprocess call outside of the slice loop (2017). If I fix that in the py3 version, it's fast again. I'll make these changes in a new branch.

**Comment by crubb** [comment]
1. 40s for Python 2.7.15 and 46s for Python 3.7.2 (yes, with the moved subprocess call). No huge difference.
2. `fslreorient2std` has been used. I'm double checking the issue, give me a few minutes.

**Comment by crubb** [comment]
ad 2)

We used the HCP-Pipeline, therefore `fslreorient2std` had been used. 

I just remember that the axis flipping was not noticeable in the `trilinear.nii.gz`, but only noted after running `convertwarp`/`applywarp` after `grad_unwarp.py` (i.e. https://github.com/Washington-University/HCPpipelines/blob/3b5daee4f133fb027fadcb5ba2c70cb37127cdcc/global/scripts/GradientDistortionUnwarp.sh#L112-L114).

I just double checked using `FSLeyes`:
- `trilinear.nii.gz` is correctly orientated.
- The result after `convertwarp`/`applywarp` (i.e. `T1w1_gdc.nii.gz`) is flipped.

**Comment by coalsont** [comment]
The FSL registration/resampling coordinate system is prone to shifting things when you aren't careful with volume spaces, but I haven't seen it flip something.  They add a flip when the coordinate system is left-handed, but if that flip were in the wrong axis, I would expect a 180 degree rotation rather than a simple flip.  Can you post the sform/qform of the inputs to convertwarp and applywarp?

**Comment by crubb** [comment]
# T1w1

This is after `fslreorient2std`.

```
$ fslhd T1w1.nii.gz
filename	T1w1.nii.gz

sizeof_hdr	348
data_type	INT16
dim0		3
dim1		208
dim2		300
dim3		320
dim4		1
dim5		1
dim6		1
dim7		1
vox_units	mm
time_units	s
datatype	4
nbyper		2
bitpix		16
pixdim0		1.000000
pixdim1		0.800000
pixdim2		0.800000
pixdim3		0.800000
pixdim4		2.500000
pixdim5		0.000000
pixdim6		0.000000
pixdim7		0.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	1
freq_dim	2
slice_dim	3
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.799956 -0.008197 0.001892 -83.909576
qto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
qto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
sto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
sto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		TE=2.2;Time=181315.793;phase=1
aux_file
```

# T1w1_vol1
```
$ fslhd T1w1_vol1.nii.gz
filename	T1w1_vol1.nii.gz

sizeof_hdr	348
data_type	INT16
dim0		3
dim1		208
dim2		300
dim3		320
dim4		1
dim5		1
dim6		1
dim7		1
vox_units	mm
time_units	s
datatype	4
nbyper		2
bitpix		16
pixdim0		1.000000
pixdim1		0.800000
pixdim2		0.800000
pixdim3		0.800000
pixdim4		2.500000
pixdim5		0.000000
pixdim6		0.000000
pixdim7		0.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	0
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.799956 -0.008197 0.001892 -83.909576
qto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
qto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
sto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
sto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		6.0.2:a4f562d9
aux_file
```

# Python 2
## trilinear-py2
```
$ fslhd trilinear-py2.nii.gz
filename	trilinear-py2.nii.gz

sizeof_hdr	348
data_type	FLOAT32
dim0		3
dim1		208
dim2		300
dim3		320
dim4		1
dim5		1
dim6		1
dim7		1
vox_units	Unknown
time_units	Unknown
datatype	16
nbyper		4
bitpix		32
pixdim0		1.000000
pixdim1		0.800002
pixdim2		0.800000
pixdim3		0.800000
pixdim4		1.000000
pixdim5		1.000000
pixdim6		1.000000
pixdim7		1.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	0
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Unknown
qform_code	0
qto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
qto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
qto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Unknown
sform_code	2
sto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
sto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
sto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip
aux_file
```

## transform-py2
```
$ fslhd transform-py2.nii.gz
filename	transform-py2.nii.gz

sizeof_hdr	348
data_type	FLOAT32
dim0		4
dim1		208
dim2		300
dim3		320
dim4		3
dim5		1
dim6		1
dim7		1
vox_units	mm
time_units	s
datatype	16
nbyper		4
bitpix		32
pixdim0		1.000000
pixdim1		0.800002
pixdim2		0.800000
pixdim3		0.800000
pixdim4		1.000000
pixdim5		1.000000
pixdim6		1.000000
pixdim7		1.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	0
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Unknown
qform_code	0
qto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
qto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
qto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Unknown
sform_code	2
sto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
sto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
sto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		6.0.2:a4f562d9
aux_file
```

## T1w1_gdc-py2

```
$ fslhd T1w1_gdc-py2.nii.gz
filename	T1w1_gdc-py2.nii.gz

sizeof_hdr	348
data_type	INT16
dim0		3
dim1		208
dim2		300
dim3		320
dim4		1
dim5		1
dim6		1
dim7		1
vox_units	mm
time_units	s
datatype	4
nbyper		2
bitpix		16
pixdim0		1.000000
pixdim1		0.800000
pixdim2		0.800000
pixdim3		0.800000
pixdim4		2.500000
pixdim5		0.000000
pixdim6		0.000000
pixdim7		0.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	0
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.799956 -0.008197 0.001892 -83.909576
qto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
qto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
sto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
sto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		6.0.2:a4f562d9
aux_file
```

# Python 3
## trilinear-py3
```
$ fslhd trilinear-py3.nii.gz
filename	trilinear-py3.nii.gz

sizeof_hdr	348
data_type	FLOAT32
dim0		3
dim1		208
dim2		300
dim3		320
dim4		1
dim5		1
dim6		1
dim7		1
vox_units	Unknown
time_units	Unknown
datatype	16
nbyper		4
bitpix		32
pixdim0		1.000000
pixdim1		0.800002
pixdim2		0.800000
pixdim3		0.800000
pixdim4		1.000000
pixdim5		1.000000
pixdim6		1.000000
pixdim7		1.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	0
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Unknown
qform_code	0
qto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
qto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
qto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Unknown
sform_code	2
sto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
sto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
sto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip
aux_file
```

## transform-py3
```
$ fslhd transform-py3.nii.gz
filename	transform-py3.nii.gz

sizeof_hdr	348
data_type	FLOAT32
dim0		4
dim1		208
dim2		300
dim3		320
dim4		3
dim5		1
dim6		1
dim7		1
vox_units	mm
time_units	s
datatype	16
nbyper		4
bitpix		32
pixdim0		1.000000
pixdim1		0.800002
pixdim2		0.800000
pixdim3		0.800000
pixdim4		1.000000
pixdim5		1.000000
pixdim6		1.000000
pixdim7		1.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	0
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Unknown
qform_code	0
qto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
qto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
qto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Unknown
sform_code	2
sto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
sto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
sto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		6.0.2:a4f562d9
aux_file
```

## T1w1_gdc-py3
```
$ fslhd T1w1_gdc-py3.nii.gz
filename	T1w1_gdc-py3.nii.gz

sizeof_hdr	348
data_type	INT16
dim0		3
dim1		208
dim2		300
dim3		320
dim4		1
dim5		1
dim6		1
dim7		1
vox_units	mm
time_units	s
datatype	4
nbyper		2
bitpix		16
pixdim0		1.000000
pixdim1		0.800000
pixdim2		0.800000
pixdim3		0.800000
pixdim4		2.500000
pixdim5		0.000000
pixdim6		0.000000
pixdim7		0.000000
vox_offset	352
cal_max		0.000000
cal_min		0.000000
scl_slope	1.000000
scl_inter	0.000000
phase_dim	0
freq_dim	0
slice_dim	0
slice_name	Unknown
slice_code	0
slice_start	0
slice_end	0
slice_duration	0.000000
toffset		0.000000
intent		Unknown
intent_code	0
intent_name
intent_p1	0.000000
intent_p2	0.000000
intent_p3	0.000000
qform_name	Scanner Anat
qform_code	1
qto_xyz:1	0.799956 -0.008197 0.001892 -83.909576
qto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
qto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
qto_xyz:4	0.000000 0.000000 0.000000 1.000000
qform_xorient	Left-to-Right
qform_yorient	Posterior-to-Anterior
qform_zorient	Inferior-to-Superior
sform_name	Scanner Anat
sform_code	1
sto_xyz:1	0.799957 -0.008197 0.001892 -83.909576
sto_xyz:2	0.008253 0.799554 -0.025390 -95.259979
sto_xyz:3	-0.001631 0.025408 0.799595 -118.930893
sto_xyz:4	0.000000 0.000000 0.000000 1.000000
sform_xorient	Left-to-Right
sform_yorient	Posterior-to-Anterior
sform_zorient	Inferior-to-Superior
file_type	NIFTI-1+
file_code	1
descrip		6.0.2:a4f562d9
aux_file
```

**Comment by coalsont** [comment]
Skimming, those certainly look like they all have identical sform/qform.  Perhaps the fsl commands should be tested against fsl5 for consistency?  You could also open the warpfield as a volume file, figure out whether it is relative or absolute convention (and/or convert it to relative so that non-flip is basically zeros), and check whether it truly encodes a flip (though FSL's coordinate system is RPI, if I recall...looking through our code, they apply a flip for *right*-handed coordinate systems (which these volumes are), not left, so I had that backwards).

**Comment by crubb** [comment]
I just confirmed, that the flip also happens with FSL 5.0.11 - but, sorry, you lost me on the rest ;) I loaded the `fullWarp_abs.nii.gz` files I generated with the Python 2 and Python 3 gradunwarp versions in FSLeyes, and it shows that the white/black gradient is flipped.

**Comment by coalsont** [comment]
Okay, that suggests that python3 is causing gradunwarp to actually put a flip into one of its output files, so we'll have to track down where the python math gets a different answer.  You can ignore what I said about fsl, since it isn't causing a change here.

**Comment by kjamison** [comment]
The inputs I tried it on are all RPI (fsl's typical expectation, for which `fslorient` returns `RADIOLOGICAL`). Your data is LPI which should return `NEUROLOGICAL`. In unwarp_resample.py, there's an explicit x-flip for NEUROLOGICAL:

```
        outputOrient=subprocess.Popen(['fslorient', self.name], stdout=subprocess.PIPE).communicate()[0]
        if outputOrient.strip() == 'NEUROLOGICAL':
            # if neurological then flip x coordinate (both here in premat and later in postmat)
            m_vox2fsl = np.array([[-1.0*pixdim1, 0.0, 0.0, pixdim1*(dim1-1)],
...
```

This seems to be a likely candidate? I don't understand why this would behave any differently under python2 or python3 though. Since this is in the chunk of code that is MOVED in the python3 version (making it slower if you don't then move it back outside of the loop), it might be worth it to add a print statement in this section in both you python2 and python3 versions of the code just to confirm it's running in both cases and is returning the same value? And maybe print out the m_vox2fsl transform in both cases as well?

**Comment by crubb** [comment]
What puzzles me a little, is that the `trilinear.nii.gz` generated with either Python 2 or 3 do not show the flip? Why is it only apparent after FSL kicks in?

**Edit:** Just to confirm, `fslorient` returns `NEUROLOGICAL` on all the files.

**Comment by kjamison** [comment]
I don't think the `m_vox2fsl` transform is used at all in creating or saving the original unwarped output (in this case `trilinear.nii.gz`). variables `im_`->`im2`->`out` in `non_linear_unwarp_siemens` in `unwarp_resample.py` only use the `vrcsw` transform. 

`m_vox2fsl` is only used in creating `vfsl` that is used for `fullWarp`.

I'm not sure at first glance if that is a problem or the expected behavior. Still doesn't explain why python2 and python3 are any different though.

**Comment by kjamison** [comment]
I just created a [py3 branch](../tree/py3) that merges these python3 changes with the latest commits from the master. It also adds one more change for argparse compatibility in python3, an explicit error check for missing FSL dependencies, and a logging output when it detects NEUROLOGICAL orientation (and performs an x-axis flip in fullWarp_abs).

I'm still not clear why this flip would behave any different in python2 vs python3, which we should settle before the final merge.

**Comment by mharms** [comment]
I haven't tried to follow all the details, but are you saying @kjamison that the results of `gradient_unwarp.py` are not identical between python 2 and 3?  Is it just that the "orientation" as returned by `fslorient` is different, but the R/L/A/P/S/I labels in `fslview` are all still correct?  Or are the labels themselves swapped relative to the correct anatomy?

**Comment by kjamison** [comment]
The problem is that in python3 the orientation check returns `b'NEUROLOGICAL'` instead of `'NEUROLOGICAL'`, which then fails the `if outputOrient.strip() == 'NEUROLOGICAL":` test in `unwarp_resample.py:212`. This can be fixed by changing the test to `if outputOrient.strip() == b'NEUROLOGICAL":` which apparently works identically in python2 and python3 (python2 just ignores the `b`)

**Comment by kjamison** [comment]
I just updated the [py3 branch](../tree/py3) with this change. It definitely produces identical output for my LPI scans in py2 and py3. @crubb do you want to test this on your data and confirm that it solves your problem?

**Comment by crubb** [comment]
Looking good:

`gradunwarp-INFO: Input volume is NEUROLOGICAL orientation. Flipping x-axis in output fullWarp_abs.nii.gz`.

Our images are not flipped anymore using the `py3` gradunwarp branch.

---

This makes sense after all, Python 2 supposdely did output a text string (I could not find it in the docs, only on stackoverflow), Python 3 outputs a byte string:


> Popen.stdout
> If the stdout argument was PIPE, this attribute is a readable stream object as returned by open(). Reading from the stream provides output from the child process. If the encoding or errors arguments were specified or the universal_newlines argument was True, the stream is a text stream, otherwise it is a byte stream.

Therefore the matching with the `b` prefix is now needed, which is indeed ignored by Python 2:

> [...] A prefix of 'b' or 'B' is ignored in Python 2; it indicates that the literal should become a bytes literal in Python 3 (e.g. when code is automatically converted with 2to3). [...]

(https://docs.python.org/2/reference/lexical_analysis.html#string-literals)

**Comment by mharms** [comment]
Sounds like this is perhaps done?  We should update the `version.txt` file to v1.2.0, and update any version related info in the python code itself -- a quick search indicates that `setup.py` and `gradunwarp/core/globals.py` have version tags that are currently "HCP-1.0.3" but should be updated to "HCP-1.2.0".  (Those version strings were not updated when the v1.1.0 release was created).

**Comment by mharms** [comment]
Oh yeah, an updated README would be good as well.

**Comment by glasserm** [comment]
I agree. Who manages this repo, Keith?

**Comment by kjamison** [comment]
I just merged the py3 branch and updated version numbers to 1.2.0

**Comment by kjamison** [comment]
And just created a new 1.2.0 release: [https://github.com/Washington-University/gradunwarp/releases/tag/v1.2.0](releases/tag/v1.2.0)

**Comment by mharms** [comment]
You confirmed that building a py2 version from scratch still works with the revised code as well, right? (As opposed to just comparing a py3 version against an old, already existing py2 build?)

**Comment by kjamison** [comment]
Yes I built with py2 and py3 from scratch on clean virtual machines and confirmed the results were identical

**Comment by mharms** [comment]
Great.  Thanks for doing this!

**Pull request merged**
